### ISSUE TITLE
dep init does not work

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/vg#14]
`dep init` does not work when vg is activated (path is not in GOPATH)

workaround:

```
vg globalExec -- dep init
```

**Comment by JelteF** [comment]
This problem is only when using full isolation mode and the workaround is now described in the README:

https://github.com/GetStream/vg#dep-commands

**Comment by cvigo** [comment]
it is not a typo??

https://github.com/GetStream/vg#dep-commands says
`vg globalExec -- vg init`

**Comment by JelteF** [comment]
Good find, it was indeed some mistake in the repo. And actually the `--` shouldn't be used with `globalExec`. Fixed it now in the README.
