### ISSUE TITLE
go list incorrect

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/vg#16]
using 0.6.5 the output of `go list ./...` is incorrect
eg.

`github.com/goadapp/goad` is listed as `_/Users/tommaso/src/go_development/src/github.com/goadapp/goad`

**Comment by JelteF** [comment]
This is caused by using full isolation mode. A workaround is to install `bindfs` and use the absolute package path:

```
go list github.com/goadapp/goad/...
```

This is also described in the README now: https://github.com/GetStream/vg#relative-packages-in-commands
