### ISSUE TITLE
Publish binary executable of vg?

### ISSUE THREAD

**Issue by cheungpat** [GetStream/vg#32]
`dep` publish binary executable on GitHub for each version. It would be great if `vg` can do the same too. This allows installation specific version of `vg` in CI or via homebrew.

`dep` build the executables using travis. There travis script is here: https://github.com/golang/dep/blob/master/.travis.yml

**Comment by JelteF** [comment]
Good point, looking into this for the next release (which should be soon).

**Comment by JelteF** [comment]
I just released v0.8.0 including dependencies built by Travis: https://github.com/GetStream/vg/releases/tag/v0.8.0. So I'm closing this.
