### ISSUE TITLE
vg environment name does not display in the zsh

### ISSUE THREAD

**Issue by kinghadi** [GetStream/vg#36]
Hi,

I'm using `POWERLEVEL9K` theme on zsh. When I activate a virtual environment, the theme doesn't change to show the name of the current environment. I sometimes forgot to deactivate it. How to set up zsh for showing the name of activated environment?

thanks

P.S: I'm using OSX and my zsh is the latest version.

**Comment by JelteF** [comment]
Closing this as I think this is clear now. Feel free to reopen if you still have issues.

**Comment by kinghadi** [comment]
I fixed it. Thank you for `$VIRTUALGO` variable. I add the following to my `.zshrc`:
```bash
zsh_vg_env_name(){
    local color='%F{yellow}'
    if [ ! -z "$VIRTUALGO" ]; then
        echo -n "%{$color%}$VIRTUALGO%{%f%}"
    fi
}

POWERLEVEL9K_CUSTOM_VG_ENV_NAME="zsh_vg_env_name"
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status custom_vg_env_name root_indicator background_jobs history time)
```
