### ISSUE TITLE
Editing other packages

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/vg#5]
The VG version of pip install -e . isn't clearly explained. Say that I'm working on a package and want to clone and edit one of the dependencies, how do i do that with VG?

Tommaso showed me one solution, we should document it.

**Comment by JelteF** [comment]
Maybe it's not clear enough but check the README for the "vg uninstall" command

**Comment by JelteF** [comment]
I created a pull request (#8) that includes a better solution for this issue.

**Comment by JelteF** [comment]
Fixed now with #8 being merged
